ALTER TABLE company_hrs
    ADD COLUMN IF NOT EXISTS company_name TEXT,
    ADD COLUMN IF NOT EXISTS activity_type TEXT,
    ADD COLUMN IF NOT EXISTS company_type TEXT,
    ADD COLUMN IF NOT EXISTS employee_count INT,
    ADD COLUMN IF NOT EXISTS country TEXT,
    ADD COLUMN IF NOT EXISTS market TEXT,
    ADD COLUMN IF NOT EXISTS web_site TEXT,
    ADD COLUMN IF NOT EXISTS about TEXT,
    ADD COLUMN IF NOT EXISTS logo_url TEXT,
    ADD COLUMN IF NOT EXISTS instagram TEXT,
    DROP COLUMN IF EXISTS company_id;

DROP TABLE IF EXISTS company_texts CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
