CREATE TABLE IF NOT EXISTS normalization_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT NOT NULL,
    source_value TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(category, source_value)
);
CREATE INDEX idx_norm_rules_category ON normalization_rules(category);
CREATE INDEX idx_norm_rules_source ON normalization_rules(source_value);
CREATE INDEX idx_norm_rules_normalized ON normalization_rules(normalized_value);

-- category=role: from roleNormalization
INSERT INTO normalization_rules (category, source_value, normalized_value) VALUES
    ('role', 'golang', 'backend developer'),
    ('role', 'backend engineer', 'backend developer'),
    ('role', 'backend разработчик', 'backend developer'),
    ('role', 'бэкенд разработчик', 'backend developer'),
    ('role', 'golang developer', 'backend developer'),
    ('role', 'go developer', 'backend developer'),
    ('role', 'java developer', 'backend developer'),
    ('role', 'python developer', 'backend developer'),
    ('role', 'node.js developer', 'backend developer'),
    ('role', 'php developer', 'backend developer'),
    ('role', 'c# developer', 'backend developer'),
    ('role', '.net developer', 'backend developer'),
    ('role', 'software engineer', 'software engineer'),
    ('role', 'full-stack', 'fullstack developer'),
    ('role', 'full stack', 'fullstack developer'),
    ('role', 'fullstack', 'fullstack developer'),
    ('role', 'frontend engineer', 'frontend developer'),
    ('role', 'frontend разработчик', 'frontend developer'),
    ('role', 'фронтенд разработчик', 'frontend developer'),
    ('role', 'react developer', 'frontend developer'),
    ('role', 'vue developer', 'frontend developer'),
    ('role', 'angular developer', 'frontend developer'),
    ('role', 'ui developer', 'frontend developer'),
    ('role', 'mobile developer', 'mobile developer'),
    ('role', 'ios developer', 'mobile developer'),
    ('role', 'android developer', 'mobile developer'),
    ('role', 'flutter developer', 'mobile developer'),
    ('role', 'react native developer', 'mobile developer'),
    ('role', 'data scientist', 'data scientist'),
    ('role', 'data analyst', 'data analyst'),
    ('role', 'data engineer', 'data engineer'),
    ('role', 'ml engineer', 'ml engineer'),
    ('role', 'machine learning', 'ml engineer'),
    ('role', 'qa engineer', 'qa engineer'),
    ('role', 'test engineer', 'qa engineer'),
    ('role', 'quality assurance', 'qa engineer'),
    ('role', 'тестировщик', 'qa engineer'),
    ('role', 'devops engineer', 'devops engineer'),
    ('role', 'sre', 'devops engineer'),
    ('role', 'site reliability', 'devops engineer'),
    ('role', 'infrastructure', 'devops engineer'),
    ('role', 'product manager', 'product manager'),
    ('role', 'project manager', 'project manager'),
    ('role', 'ui/ux', 'designer'),
    ('role', 'ux designer', 'designer'),
    ('role', 'ui designer', 'designer'),
    ('role', 'graphic designer', 'designer'),
    ('role', 'дизайнер', 'designer'),
    ('role', 'system administrator', 'system administrator'),
    ('role', 'системный администратор', 'system administrator'),
    ('role', 'dba', 'database administrator'),
    ('role', 'database administrator', 'database administrator'),
    ('role', 'technical writer', 'technical writer'),
    ('role', 'business analyst', 'business analyst'),
    ('role', 'бизнес-аналитик', 'business analyst'),
    ('role', 'cyber security', 'security engineer'),
    ('role', 'security engineer', 'security engineer'),
    ('role', 'информационная безопас', 'security engineer'),
    ('role', 'game developer', 'game developer'),
    ('role', 'embedded', 'embedded developer'),
    ('role', 'tech lead', 'tech lead'),
    ('role', 'team lead', 'tech lead'),
    ('role', 'тимлид', 'tech lead'),
    ('role', 'тех лид', 'tech lead'),
    ('role', 'архитектор', 'software architect'),
    ('role', 'architect', 'software architect'),
    ('role', 'cto', 'cto'),
    ('role', 'vp of engineering', 'vp engineering'),
    ('role', 'head of', 'head of engineering'),
    ('role', 'marketing', 'marketing specialist'),
    ('role', 'маркетолог', 'marketing specialist'),
    ('role', 'hr manager', 'hr manager'),
    ('role', 'recruiter', 'recruiter'),
    ('role', 'рекрутер', 'recruiter')
ON CONFLICT DO NOTHING;

-- category=role_family: from roleFamilies (inverted)
INSERT INTO normalization_rules (category, source_value, normalized_value) VALUES
    -- backend
    ('role_family', 'backend', 'backend'),
    ('role_family', 'golang', 'backend'),
    ('role_family', 'java developer', 'backend'),
    ('role_family', 'python developer', 'backend'),
    ('role_family', 'node.js', 'backend'),
    ('role_family', 'php', 'backend'),
    ('role_family', 'c#', 'backend'),
    ('role_family', '.net', 'backend'),
    ('role_family', 'software engineer', 'backend'),
    ('role_family', 'fullstack', 'backend'),
    -- frontend
    ('role_family', 'frontend', 'frontend'),
    ('role_family', 'react developer', 'frontend'),
    ('role_family', 'vue', 'frontend'),
    ('role_family', 'angular', 'frontend'),
    ('role_family', 'ui developer', 'frontend'),
    ('role_family', 'fullstack', 'frontend'),
    -- mobile
    ('role_family', 'mobile', 'mobile'),
    ('role_family', 'ios', 'mobile'),
    ('role_family', 'android', 'mobile'),
    ('role_family', 'flutter', 'mobile'),
    ('role_family', 'react native', 'mobile'),
    -- data
    ('role_family', 'data scientist', 'data'),
    ('role_family', 'data analyst', 'data'),
    ('role_family', 'data engineer', 'data'),
    ('role_family', 'ml engineer', 'data'),
    ('role_family', 'machine learning', 'data'),
    -- qa
    ('role_family', 'qa', 'qa'),
    ('role_family', 'test', 'qa'),
    ('role_family', 'quality assurance', 'qa'),
    -- devops
    ('role_family', 'devops', 'devops'),
    ('role_family', 'sre', 'devops'),
    ('role_family', 'site reliability', 'devops'),
    ('role_family', 'infrastructure', 'devops'),
    ('role_family', 'system administrator', 'devops'),
    -- pm
    ('role_family', 'product manager', 'pm'),
    ('role_family', 'project manager', 'pm'),
    -- design
    ('role_family', 'designer', 'design'),
    ('role_family', 'ui/ux', 'design'),
    ('role_family', 'ux', 'design'),
    ('role_family', 'graphic', 'design'),
    -- security
    ('role_family', 'security', 'security'),
    ('role_family', 'cyber', 'security'),
    -- other
    ('role_family', 'technical writer', 'other'),
    ('role_family', 'business analyst', 'other'),
    ('role_family', 'marketing', 'other'),
    ('role_family', 'hr', 'other'),
    ('role_family', 'recruiter', 'other'),
    ('role_family', 'game developer', 'other'),
    ('role_family', 'embedded', 'other')
ON CONFLICT DO NOTHING;

-- category=skill: from skillNormalization
INSERT INTO normalization_rules (category, source_value, normalized_value) VALUES
    ('skill', 'postgres', 'postgresql'),
    ('skill', 'postgresql', 'postgresql'),
    ('skill', 'mongo', 'mongodb'),
    ('skill', 'mongodb', 'mongodb'),
    ('skill', 'k8s', 'kubernetes'),
    ('skill', 'kubernetes', 'kubernetes'),
    ('skill', 'ci/cd', 'ci_cd'),
    ('skill', 'cicd', 'ci_cd'),
    ('skill', 'ci cd', 'ci_cd'),
    ('skill', 'grpc', 'grpc'),
    ('skill', 'rest api', 'rest_api'),
    ('skill', 'restful', 'rest_api'),
    ('skill', 'rest', 'rest_api'),
    ('skill', 'docker', 'docker'),
    ('skill', 'react', 'react'),
    ('skill', 'reactjs', 'react'),
    ('skill', 'react.js', 'react'),
    ('skill', 'vue', 'vuejs'),
    ('skill', 'vue.js', 'vuejs'),
    ('skill', 'vuejs', 'vuejs'),
    ('skill', 'angular', 'angular'),
    ('skill', 'typescript', 'typescript'),
    ('skill', 'ts', 'typescript'),
    ('skill', 'javascript', 'javascript'),
    ('skill', 'js', 'javascript'),
    ('skill', 'python', 'python'),
    ('skill', 'golang', 'go'),
    ('skill', 'go', 'go'),
    ('skill', 'java', 'java'),
    ('skill', 'c#', 'csharp'),
    ('skill', 'c sharp', 'csharp'),
    ('skill', '.net', 'dotnet'),
    ('skill', 'dotnet', 'dotnet'),
    ('skill', 'asp.net', 'dotnet'),
    ('skill', 'node', 'nodejs'),
    ('skill', 'node.js', 'nodejs'),
    ('skill', 'nodejs', 'nodejs'),
    ('skill', 'express', 'expressjs'),
    ('skill', 'express.js', 'expressjs'),
    ('skill', 'flutter', 'flutter'),
    ('skill', 'dart', 'dart'),
    ('skill', 'kotlin', 'kotlin'),
    ('skill', 'swift', 'swift'),
    ('skill', 'redis', 'redis'),
    ('skill', 'kafka', 'kafka'),
    ('skill', 'rabbitmq', 'rabbitmq'),
    ('skill', 'aws', 'aws'),
    ('skill', 'gcp', 'gcp'),
    ('skill', 'azure', 'azure'),
    ('skill', 'terraform', 'terraform'),
    ('skill', 'nginx', 'nginx'),
    ('skill', 'linux', 'linux'),
    ('skill', 'git', 'git'),
    ('skill', 'mysql', 'mysql'),
    ('skill', 'sqlite', 'sqlite'),
    ('skill', 'elasticsearch', 'elasticsearch'),
    ('skill', 'graphql', 'graphql'),
    ('skill', 'next.js', 'nextjs'),
    ('skill', 'nextjs', 'nextjs'),
    ('skill', 'tailwind', 'tailwind'),
    ('skill', 'tailwind css', 'tailwind'),
    ('skill', 'figma', 'figma'),
    ('skill', 'storybook', 'storybook'),
    ('skill', 'firebase', 'firebase'),
    ('skill', 'bloc', 'bloc'),
    ('skill', 'riverpod', 'riverpod'),
    ('skill', 'pandas', 'pandas'),
    ('skill', 'numpy', 'numpy'),
    ('skill', 'scikit-learn', 'scikit_learn'),
    ('skill', 'sklearn', 'scikit_learn'),
    ('skill', 'tableau', 'tableau'),
    ('skill', 'power bi', 'powerbi'),
    ('skill', 'powerbi', 'powerbi'),
    ('skill', 'jupyter', 'jupyter')
ON CONFLICT DO NOTHING;

-- category=company: from companyNormalization
INSERT INTO normalization_rules (category, source_value, normalized_value) VALUES
    ('company', 'yandex', 'yandex'),
    ('company', 'яндекс', 'yandex'),
    ('company', 'google', 'google'),
    ('company', 'meta', 'meta'),
    ('company', 'facebook', 'meta'),
    ('company', 'apple', 'apple'),
    ('company', 'amazon', 'amazon'),
    ('company', 'microsoft', 'microsoft'),
    ('company', 'epam', 'epam'),
    ('company', 'kaspersky', 'kaspersky'),
    ('company', 'jetbrains', 'jetbrains'),
    ('company', 'tinkoff', 'tinkoff'),
    ('company', 't-bank', 'tinkoff'),
    ('company', 'vk', 'vk'),
    ('company', 'revolut', 'revolut'),
    ('company', 'stripe', 'stripe'),
    ('company', 'payme', 'payme'),
    ('company', 'click', 'click'),
    ('company', 'uzum', 'uzum'),
    ('company', 'mytaxi', 'mytaxi'),
    ('company', 'yandex go', 'mytaxi'),
    ('company', 'billz', 'billz'),
    ('company', 'humans', 'humans'),
    ('company', 'apelsin', 'apelsin'),
    ('company', 'osontaxi', 'osontaxi'),
    ('company', 'korzinka', 'korzinka'),
    ('company', 'artel', 'artel'),
    ('company', 'uzauto', 'uzauto'),
    ('company', 'ucell', 'ucell'),
    ('company', 'beeline', 'beeline_uz'),
    ('company', 'it park', 'it_park'),
    ('company', 'mediapark', 'mediapark'),
    ('company', 'kapitalbank', 'kapitalbank'),
    ('company', 'fido biznes', 'fido_biznes'),
    ('company', 'fido', 'fido_biznes')
ON CONFLICT DO NOTHING;

-- category=domain: from domainKeywords (inverted)
INSERT INTO normalization_rules (category, source_value, normalized_value) VALUES
    -- ecommerce
    ('domain', 'ecommerce', 'ecommerce'),
    ('domain', 'e-commerce', 'ecommerce'),
    ('domain', 'online store', 'ecommerce'),
    ('domain', 'marketplace', 'ecommerce'),
    ('domain', 'магазин', 'ecommerce'),
    ('domain', 'маркетплейс', 'ecommerce'),
    ('domain', 'shop', 'ecommerce'),
    ('domain', 'retail', 'ecommerce'),
    -- payments
    ('domain', 'payment', 'payments'),
    ('domain', 'billing', 'payments'),
    ('domain', 'checkout', 'payments'),
    ('domain', 'acquiring', 'payments'),
    ('domain', 'платёж', 'payments'),
    ('domain', 'оплата', 'payments'),
    ('domain', 'transaction', 'payments'),
    -- fintech
    ('domain', 'fintech', 'fintech'),
    ('domain', 'banking', 'fintech'),
    ('domain', 'bank', 'fintech'),
    ('domain', 'lending', 'fintech'),
    ('domain', 'финтех', 'fintech'),
    ('domain', 'банк', 'fintech'),
    ('domain', 'кредит', 'fintech'),
    ('domain', 'financial', 'fintech'),
    -- logistics
    ('domain', 'logistics', 'logistics'),
    ('domain', 'delivery', 'logistics'),
    ('domain', 'shipping', 'logistics'),
    ('domain', 'логистика', 'logistics'),
    ('domain', 'доставка', 'logistics'),
    ('domain', 'transportation', 'logistics'),
    -- healthcare
    ('domain', 'health', 'healthcare'),
    ('domain', 'medical', 'healthcare'),
    ('domain', 'medicine', 'healthcare'),
    ('domain', 'здоровье', 'healthcare'),
    ('domain', 'медицин', 'healthcare'),
    -- edtech
    ('domain', 'edtech', 'edtech'),
    ('domain', 'education', 'edtech'),
    ('domain', 'learning', 'edtech'),
    ('domain', 'course', 'edtech'),
    ('domain', 'образовани', 'edtech'),
    ('domain', 'обучени', 'edtech'),
    -- enterprise
    ('domain', 'crm', 'enterprise'),
    ('domain', 'erp', 'enterprise'),
    ('domain', 'enterprise', 'enterprise'),
    ('domain', 'saas', 'enterprise'),
    ('domain', 'b2b', 'enterprise'),
    -- analytics
    ('domain', 'analytics', 'analytics'),
    ('domain', 'bi', 'analytics'),
    ('domain', 'data warehouse', 'analytics'),
    ('domain', 'dwh', 'analytics'),
    ('domain', 'аналитик', 'analytics'),
    -- gaming
    ('domain', 'gaming', 'gaming'),
    ('domain', 'game', 'gaming'),
    ('domain', 'gamedev', 'gaming'),
    ('domain', 'игр', 'gaming'),
    -- telecom
    ('domain', 'telecom', 'telecom'),
    ('domain', 'телеком', 'telecom'),
    ('domain', 'mobile operator', 'telecom'),
    ('domain', 'связь', 'telecom'),
    -- media
    ('domain', 'media', 'media'),
    ('domain', 'news', 'media'),
    ('domain', 'content', 'media'),
    ('domain', 'медиа', 'media'),
    ('domain', 'контент', 'media'),
    ('domain', 'новост', 'media'),
    -- taxi
    ('domain', 'taxi', 'taxi'),
    ('domain', 'ride', 'taxi'),
    ('domain', 'такси', 'taxi')
ON CONFLICT DO NOTHING;
