// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: education_items.sql

package educationitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEducationItem = `-- name: CreateEducationItem :one
INSERT INTO education_items (id, user_id, institution, degree, field_of_study, start_date, end_date, location, item_order, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, user_id, institution, degree, field_of_study, start_date, end_date, location, item_order, updated_at
`

type CreateEducationItemParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Institution  string
	Degree       string
	FieldOfStudy pgtype.Text
	StartDate    pgtype.Text
	EndDate      pgtype.Text
	Location     pgtype.Text
	ItemOrder    int32
}

func (q *Queries) CreateEducationItem(ctx context.Context, arg CreateEducationItemParams) (EducationItem, error) {
	row := q.db.QueryRow(ctx, createEducationItem,
		arg.ID,
		arg.UserID,
		arg.Institution,
		arg.Degree,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.ItemOrder,
	)
	var i EducationItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Institution,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEducationItem = `-- name: DeleteEducationItem :exec
DELETE FROM education_items WHERE id = $1
`

func (q *Queries) DeleteEducationItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEducationItem, id)
	return err
}

const deleteEducationItemsByUser = `-- name: DeleteEducationItemsByUser :exec
DELETE FROM education_items WHERE user_id = $1
`

func (q *Queries) DeleteEducationItemsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEducationItemsByUser, userID)
	return err
}

const getEducationItemByID = `-- name: GetEducationItemByID :one
SELECT id, user_id, institution, degree, field_of_study, start_date, end_date, location, item_order, updated_at
FROM education_items
WHERE id = $1
`

func (q *Queries) GetEducationItemByID(ctx context.Context, id pgtype.UUID) (EducationItem, error) {
	row := q.db.QueryRow(ctx, getEducationItemByID, id)
	var i EducationItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Institution,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listEducationItemsByUser = `-- name: ListEducationItemsByUser :many
SELECT id, user_id, institution, degree, field_of_study, start_date, end_date, location, item_order, updated_at
FROM education_items
WHERE user_id = $1
ORDER BY item_order
`

func (q *Queries) ListEducationItemsByUser(ctx context.Context, userID pgtype.UUID) ([]EducationItem, error) {
	rows, err := q.db.Query(ctx, listEducationItemsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EducationItem
	for rows.Next() {
		var i EducationItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Institution,
			&i.Degree,
			&i.FieldOfStudy,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.ItemOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEducationItem = `-- name: UpdateEducationItem :one
UPDATE education_items
SET institution = COALESCE(NULLIF($1, ''), institution),
    degree = COALESCE(NULLIF($2, ''), degree),
    field_of_study = COALESCE(NULLIF($3, ''), field_of_study),
    start_date = COALESCE(NULLIF($4, ''), start_date),
    end_date = COALESCE(NULLIF($5, ''), end_date),
    location = COALESCE(NULLIF($6, ''), location),
    item_order = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, user_id, institution, degree, field_of_study, start_date, end_date, location, item_order, updated_at
`

type UpdateEducationItemParams struct {
	Institution  interface{}
	Degree       interface{}
	FieldOfStudy interface{}
	StartDate    interface{}
	EndDate      interface{}
	Location     interface{}
	ItemOrder    int32
	ID           pgtype.UUID
}

func (q *Queries) UpdateEducationItem(ctx context.Context, arg UpdateEducationItemParams) (EducationItem, error) {
	row := q.db.QueryRow(ctx, updateEducationItem,
		arg.Institution,
		arg.Degree,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
		arg.ItemOrder,
		arg.ID,
	)
	var i EducationItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Institution,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}
