services:
  hr-ai:
    build: .
    network_mode: host
    env_file:
      - .env
    depends_on:
      seed:
        condition: service_completed_successfully
    restart: unless-stopped

  seed:
    build: .
    command: ./seeder
    network_mode: host
    env_file:
      - .env
