FROM golang:1.25-alpine

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Pre-copy go.mod and go.sum for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Run Air
CMD ["air", "-c", ".air.toml"]
