// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vacancies.sql

package vacancies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVacancies = `-- name: CountVacancies :one
SELECT count(*) FROM vacancies
`

func (q *Queries) CountVacancies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVacancies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVacanciesByCompany = `-- name: CountVacanciesByCompany :one
SELECT count(*) FROM vacancies WHERE company_id = $1
`

func (q *Queries) CountVacanciesByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVacanciesByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVacancy = `-- name: CreateVacancy :one
INSERT INTO vacancies (
    id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, now()
)
RETURNING id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
`

type CreateVacancyParams struct {
	ID             pgtype.UUID
	HrID           pgtype.UUID
	CompanyID      pgtype.UUID
	SalaryMin      pgtype.Int4
	SalaryMax      pgtype.Int4
	SalaryCurrency string
	ExperienceMin  pgtype.Int4
	ExperienceMax  pgtype.Int4
	Format         string
	Schedule       string
	Phone          pgtype.Text
	Telegram       pgtype.Text
	Email          pgtype.Text
	Address        pgtype.Text
	Status         string
	SourceLang     string
}

func (q *Queries) CreateVacancy(ctx context.Context, arg CreateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, createVacancy,
		arg.ID,
		arg.HrID,
		arg.CompanyID,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.ExperienceMin,
		arg.ExperienceMax,
		arg.Format,
		arg.Schedule,
		arg.Phone,
		arg.Telegram,
		arg.Email,
		arg.Address,
		arg.Status,
		arg.SourceLang,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.CompanyID,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.Format,
		&i.Schedule,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVacancy = `-- name: DeleteVacancy :exec
DELETE FROM vacancies WHERE id = $1
`

func (q *Queries) DeleteVacancy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancy, id)
	return err
}

const getVacancyByID = `-- name: GetVacancyByID :one
SELECT id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
FROM vacancies
WHERE id = $1
`

func (q *Queries) GetVacancyByID(ctx context.Context, id pgtype.UUID) (Vacancy, error) {
	row := q.db.QueryRow(ctx, getVacancyByID, id)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.CompanyID,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.Format,
		&i.Schedule,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}

const listVacancies = `-- name: ListVacancies :many
SELECT id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
FROM vacancies
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVacanciesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVacancies(ctx context.Context, arg ListVacanciesParams) ([]Vacancy, error) {
	rows, err := q.db.Query(ctx, listVacancies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vacancy
	for rows.Next() {
		var i Vacancy
		if err := rows.Scan(
			&i.ID,
			&i.HrID,
			&i.CompanyID,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.ExperienceMin,
			&i.ExperienceMax,
			&i.Format,
			&i.Schedule,
			&i.Phone,
			&i.Telegram,
			&i.Email,
			&i.Address,
			&i.Status,
			&i.SourceLang,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacanciesByCompany = `-- name: ListVacanciesByCompany :many
SELECT id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
FROM vacancies
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVacanciesByCompanyParams struct {
	CompanyID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListVacanciesByCompany(ctx context.Context, arg ListVacanciesByCompanyParams) ([]Vacancy, error) {
	rows, err := q.db.Query(ctx, listVacanciesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vacancy
	for rows.Next() {
		var i Vacancy
		if err := rows.Scan(
			&i.ID,
			&i.HrID,
			&i.CompanyID,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.ExperienceMin,
			&i.ExperienceMax,
			&i.Format,
			&i.Schedule,
			&i.Phone,
			&i.Telegram,
			&i.Email,
			&i.Address,
			&i.Status,
			&i.SourceLang,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacanciesByHR = `-- name: ListVacanciesByHR :many
SELECT id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
FROM vacancies
WHERE hr_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVacanciesByHRParams struct {
	HrID   pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListVacanciesByHR(ctx context.Context, arg ListVacanciesByHRParams) ([]Vacancy, error) {
	rows, err := q.db.Query(ctx, listVacanciesByHR, arg.HrID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vacancy
	for rows.Next() {
		var i Vacancy
		if err := rows.Scan(
			&i.ID,
			&i.HrID,
			&i.CompanyID,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.ExperienceMin,
			&i.ExperienceMax,
			&i.Format,
			&i.Schedule,
			&i.Phone,
			&i.Telegram,
			&i.Email,
			&i.Address,
			&i.Status,
			&i.SourceLang,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacancy = `-- name: UpdateVacancy :one
UPDATE vacancies
SET salary_min = CASE WHEN $1::INT = 0 THEN salary_min ELSE $1 END,
    salary_max = CASE WHEN $2::INT = 0 THEN salary_max ELSE $2 END,
    salary_currency = COALESCE(NULLIF($3, ''), salary_currency),
    experience_min = CASE WHEN $4::INT = 0 THEN experience_min ELSE $4 END,
    experience_max = CASE WHEN $5::INT = 0 THEN experience_max ELSE $5 END,
    format = COALESCE(NULLIF($6, ''), format),
    schedule = COALESCE(NULLIF($7, ''), schedule),
    phone = COALESCE(NULLIF($8, ''), phone),
    telegram = COALESCE(NULLIF($9, ''), telegram),
    email = COALESCE(NULLIF($10, ''), email),
    address = COALESCE(NULLIF($11, ''), address),
    status = COALESCE(NULLIF($12, ''), status)
WHERE id = $13
RETURNING id, hr_id, company_id, salary_min, salary_max, salary_currency,
    experience_min, experience_max, format, schedule,
    phone, telegram, email, address, status, source_lang, created_at
`

type UpdateVacancyParams struct {
	SalaryMin      int32
	SalaryMax      int32
	SalaryCurrency interface{}
	ExperienceMin  int32
	ExperienceMax  int32
	Format         interface{}
	Schedule       interface{}
	Phone          interface{}
	Telegram       interface{}
	Email          interface{}
	Address        interface{}
	Status         interface{}
	ID             pgtype.UUID
}

func (q *Queries) UpdateVacancy(ctx context.Context, arg UpdateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, updateVacancy,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.ExperienceMin,
		arg.ExperienceMax,
		arg.Format,
		arg.Schedule,
		arg.Phone,
		arg.Telegram,
		arg.Email,
		arg.Address,
		arg.Status,
		arg.ID,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.CompanyID,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.ExperienceMin,
		&i.ExperienceMax,
		&i.Format,
		&i.Schedule,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}
