// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: country_texts.sql

package countrytexts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCountryText = `-- name: CreateCountryText :one
INSERT INTO country_texts (
    country_id, lang, name, is_source, model_version, updated_at
) VALUES (
    $1, $2, $3, $4, $5, now()
)
RETURNING country_id, lang, name, is_source, model_version, updated_at
`

type CreateCountryTextParams struct {
	CountryID    pgtype.UUID
	Lang         string
	Name         string
	IsSource     bool
	ModelVersion pgtype.Text
}

func (q *Queries) CreateCountryText(ctx context.Context, arg CreateCountryTextParams) (CountryText, error) {
	row := q.db.QueryRow(ctx, createCountryText,
		arg.CountryID,
		arg.Lang,
		arg.Name,
		arg.IsSource,
		arg.ModelVersion,
	)
	var i CountryText
	err := row.Scan(
		&i.CountryID,
		&i.Lang,
		&i.Name,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCountryText = `-- name: DeleteCountryText :exec
DELETE FROM country_texts
WHERE country_id = $1 AND lang = $2
`

type DeleteCountryTextParams struct {
	CountryID pgtype.UUID
	Lang      string
}

func (q *Queries) DeleteCountryText(ctx context.Context, arg DeleteCountryTextParams) error {
	_, err := q.db.Exec(ctx, deleteCountryText, arg.CountryID, arg.Lang)
	return err
}

const deleteCountryTextsByCountry = `-- name: DeleteCountryTextsByCountry :exec
DELETE FROM country_texts
WHERE country_id = $1
`

func (q *Queries) DeleteCountryTextsByCountry(ctx context.Context, countryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCountryTextsByCountry, countryID)
	return err
}

const getCountryText = `-- name: GetCountryText :one
SELECT country_id, lang, name, is_source, model_version, updated_at
FROM country_texts
WHERE country_id = $1 AND lang = $2
`

type GetCountryTextParams struct {
	CountryID pgtype.UUID
	Lang      string
}

func (q *Queries) GetCountryText(ctx context.Context, arg GetCountryTextParams) (CountryText, error) {
	row := q.db.QueryRow(ctx, getCountryText, arg.CountryID, arg.Lang)
	var i CountryText
	err := row.Scan(
		&i.CountryID,
		&i.Lang,
		&i.Name,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listCountryTextsByCountry = `-- name: ListCountryTextsByCountry :many
SELECT country_id, lang, name, is_source, model_version, updated_at
FROM country_texts
WHERE country_id = $1
`

func (q *Queries) ListCountryTextsByCountry(ctx context.Context, countryID pgtype.UUID) ([]CountryText, error) {
	rows, err := q.db.Query(ctx, listCountryTextsByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountryText
	for rows.Next() {
		var i CountryText
		if err := rows.Scan(
			&i.CountryID,
			&i.Lang,
			&i.Name,
			&i.IsSource,
			&i.ModelVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountryText = `-- name: UpdateCountryText :one
UPDATE country_texts
SET name = COALESCE(NULLIF($1, ''), name),
    is_source = $2,
    model_version = $3,
    updated_at = now()
WHERE country_id = $4 AND lang = $5
RETURNING country_id, lang, name, is_source, model_version, updated_at
`

type UpdateCountryTextParams struct {
	Name         interface{}
	IsSource     bool
	ModelVersion pgtype.Text
	CountryID    pgtype.UUID
	Lang         string
}

func (q *Queries) UpdateCountryText(ctx context.Context, arg UpdateCountryTextParams) (CountryText, error) {
	row := q.db.QueryRow(ctx, updateCountryText,
		arg.Name,
		arg.IsSource,
		arg.ModelVersion,
		arg.CountryID,
		arg.Lang,
	)
	var i CountryText
	err := row.Scan(
		&i.CountryID,
		&i.Lang,
		&i.Name,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
