// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package countrytexts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID              pgtype.UUID
	EmployeeCount   pgtype.Int4
	Country         pgtype.Text
	Address         pgtype.Text
	Phone           pgtype.Text
	Telegram        pgtype.Text
	TelegramChannel pgtype.Text
	Email           pgtype.Text
	LogoUrl         pgtype.Text
	WebSite         pgtype.Text
	Instagram       pgtype.Text
	SourceLang      string
	CreatedAt       pgtype.Timestamp
}

type CompanyHr struct {
	ID           pgtype.UUID
	FirstName    string
	LastName     string
	Patronymic   pgtype.Text
	Phone        pgtype.Text
	Telegram     pgtype.Text
	TelegramID   pgtype.Text
	Email        pgtype.Text
	Position     pgtype.Text
	Status       string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	Language     string
	CompanyData  []byte
}

type CompanyText struct {
	CompanyID    pgtype.UUID
	Lang         string
	Name         string
	ActivityType string
	CompanyType  string
	About        string
	Market       string
	IsSource     bool
	ModelVersion pgtype.Text
	UpdatedAt    pgtype.Timestamp
}

type Country struct {
	ID        pgtype.UUID
	Name      string
	ShortCode string
	CreatedAt pgtype.Timestamp
}

type CountryText struct {
	CountryID    pgtype.UUID
	Lang         string
	Name         string
	IsSource     bool
	ModelVersion pgtype.Text
	UpdatedAt    pgtype.Timestamp
}

type EducationItem struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Institution  string
	Degree       string
	FieldOfStudy pgtype.Text
	StartDate    pgtype.Text
	EndDate      pgtype.Text
	Location     pgtype.Text
	ItemOrder    int32
	UpdatedAt    pgtype.Timestamp
}

type ExperienceItem struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Company   string
	Position  string
	StartDate pgtype.Text
	EndDate   pgtype.Text
	Projects  pgtype.Text
	WebSite   pgtype.Text
	ItemOrder int32
	UpdatedAt pgtype.Timestamp
}

type HrSession struct {
	ID               pgtype.UUID
	HrID             pgtype.UUID
	DeviceID         string
	RefreshTokenHash string
	FcmToken         pgtype.Text
	IpAddress        pgtype.Text
	CreatedAt        pgtype.Timestamp
	Deleted          bool
}

type ItemText struct {
	ItemID       pgtype.UUID
	ItemType     string
	Lang         string
	Description  string
	IsSource     bool
	ModelVersion pgtype.Text
	UpdatedAt    pgtype.Timestamp
}

type ProfileField struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FieldName  string
	SourceLang string
	UpdatedAt  pgtype.Timestamp
}

type ProfileFieldText struct {
	ProfileFieldID pgtype.UUID
	Lang           string
	Content        string
	IsSource       bool
	ModelVersion   pgtype.Text
	UpdatedAt      pgtype.Timestamp
}

type Skill struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID                      pgtype.UUID
	FirstName               string
	LastName                string
	Patronymic              pgtype.Text
	Phone                   pgtype.Text
	Telegram                pgtype.Text
	Email                   pgtype.Text
	Gender                  pgtype.Text
	Country                 pgtype.Text
	Region                  pgtype.Text
	Nationality             pgtype.Text
	ProfilePicUrl           pgtype.Text
	Status                  string
	TariffType              string
	JobStatus               pgtype.Text
	ActivityType            pgtype.Text
	Specializations         []string
	CreatedAt               pgtype.Timestamp
	PasswordHash            pgtype.Text
	TelegramID              pgtype.Text
	Language                string
	ProfileScore            int32
	EstimatedSalaryMin      int32
	EstimatedSalaryMax      int32
	EstimatedSalaryCurrency string
}

type UserSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	DeviceID         string
	RefreshTokenHash string
	FcmToken         pgtype.Text
	IpAddress        pgtype.Text
	CreatedAt        pgtype.Timestamp
	Deleted          bool
}

type UserSkill struct {
	UserID  pgtype.UUID
	SkillID pgtype.UUID
}

type Vacancy struct {
	ID             pgtype.UUID
	HrID           pgtype.UUID
	SalaryMin      pgtype.Int4
	SalaryMax      pgtype.Int4
	SalaryCurrency string
	ExperienceMin  pgtype.Int4
	ExperienceMax  pgtype.Int4
	Format         string
	Schedule       string
	Phone          pgtype.Text
	Telegram       pgtype.Text
	Email          pgtype.Text
	Address        pgtype.Text
	Status         string
	SourceLang     string
	CreatedAt      pgtype.Timestamp
	CountryID      pgtype.UUID
	CompanyData    []byte
}

type VacancyApplication struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	VacancyID   pgtype.UUID
	Status      string
	CoverLetter pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	SeenAt      pgtype.Timestamp
}

type VacancySkill struct {
	VacancyID pgtype.UUID
	SkillID   pgtype.UUID
}

type VacancyText struct {
	VacancyID        pgtype.UUID
	Lang             string
	Title            string
	Description      string
	Responsibilities string
	Requirements     string
	Benefits         string
	IsSource         bool
	ModelVersion     pgtype.Text
	UpdatedAt        pgtype.Timestamp
}
