// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package profilefieldtexts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProfileField struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FieldName  string
	SourceLang string
	UpdatedAt  pgtype.Timestamp
}

type ProfileFieldText struct {
	ProfileFieldID pgtype.UUID
	Lang           string
	Content        string
	IsSource       bool
	ModelVersion   pgtype.Text
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID            pgtype.UUID
	Phone         pgtype.Text
	Email         pgtype.Text
	ProfilePicUrl pgtype.Text
	CreatedAt     pgtype.Timestamp
}
