// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package profilefieldtexts

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProfileField struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FieldName  string
	SourceLang string
	UpdatedAt  pgtype.Timestamp
}

type ProfileFieldText struct {
	ProfileFieldID pgtype.UUID
	Lang           string
	Content        string
	IsSource       bool
	ModelVersion   pgtype.Text
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID              pgtype.UUID
	FirstName       string
	LastName        string
	Patronymic      pgtype.Text
	Phone           pgtype.Text
	Telegram        pgtype.Text
	Email           pgtype.Text
	Gender          pgtype.Text
	Country         pgtype.Text
	Region          pgtype.Text
	Nationality     pgtype.Text
	ProfilePicUrl   pgtype.Text
	Status          string
	TariffType      string
	JobStatus       pgtype.Text
	ActivityType    pgtype.Text
	Specializations []string
	CreatedAt       pgtype.Timestamp
}
