// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile_field_texts.sql

package profilefieldtexts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfileFieldText = `-- name: CreateProfileFieldText :one
INSERT INTO profile_field_texts (profile_field_id, lang, content, is_source, model_version, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING profile_field_id, lang, content, is_source, model_version, updated_at
`

type CreateProfileFieldTextParams struct {
	ProfileFieldID pgtype.UUID
	Lang           string
	Content        string
	IsSource       bool
	ModelVersion   pgtype.Text
}

func (q *Queries) CreateProfileFieldText(ctx context.Context, arg CreateProfileFieldTextParams) (ProfileFieldText, error) {
	row := q.db.QueryRow(ctx, createProfileFieldText,
		arg.ProfileFieldID,
		arg.Lang,
		arg.Content,
		arg.IsSource,
		arg.ModelVersion,
	)
	var i ProfileFieldText
	err := row.Scan(
		&i.ProfileFieldID,
		&i.Lang,
		&i.Content,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfileFieldText = `-- name: DeleteProfileFieldText :exec
DELETE FROM profile_field_texts
WHERE profile_field_id = $1 AND lang = $2
`

type DeleteProfileFieldTextParams struct {
	ProfileFieldID pgtype.UUID
	Lang           string
}

func (q *Queries) DeleteProfileFieldText(ctx context.Context, arg DeleteProfileFieldTextParams) error {
	_, err := q.db.Exec(ctx, deleteProfileFieldText, arg.ProfileFieldID, arg.Lang)
	return err
}

const deleteProfileFieldTextsByField = `-- name: DeleteProfileFieldTextsByField :exec
DELETE FROM profile_field_texts
WHERE profile_field_id = $1
`

func (q *Queries) DeleteProfileFieldTextsByField(ctx context.Context, profileFieldID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileFieldTextsByField, profileFieldID)
	return err
}

const getProfileFieldText = `-- name: GetProfileFieldText :one
SELECT profile_field_id, lang, content, is_source, model_version, updated_at
FROM profile_field_texts
WHERE profile_field_id = $1 AND lang = $2
`

type GetProfileFieldTextParams struct {
	ProfileFieldID pgtype.UUID
	Lang           string
}

func (q *Queries) GetProfileFieldText(ctx context.Context, arg GetProfileFieldTextParams) (ProfileFieldText, error) {
	row := q.db.QueryRow(ctx, getProfileFieldText, arg.ProfileFieldID, arg.Lang)
	var i ProfileFieldText
	err := row.Scan(
		&i.ProfileFieldID,
		&i.Lang,
		&i.Content,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfileFieldTexts = `-- name: ListProfileFieldTexts :many
SELECT profile_field_id, lang, content, is_source, model_version, updated_at
FROM profile_field_texts
WHERE profile_field_id = $1
ORDER BY is_source DESC, lang
`

func (q *Queries) ListProfileFieldTexts(ctx context.Context, profileFieldID pgtype.UUID) ([]ProfileFieldText, error) {
	rows, err := q.db.Query(ctx, listProfileFieldTexts, profileFieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileFieldText
	for rows.Next() {
		var i ProfileFieldText
		if err := rows.Scan(
			&i.ProfileFieldID,
			&i.Lang,
			&i.Content,
			&i.IsSource,
			&i.ModelVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileFieldText = `-- name: UpdateProfileFieldText :one
UPDATE profile_field_texts
SET content = $1,
    model_version = $2,
    updated_at = now()
WHERE profile_field_id = $3 AND lang = $4
RETURNING profile_field_id, lang, content, is_source, model_version, updated_at
`

type UpdateProfileFieldTextParams struct {
	Content        string
	ModelVersion   pgtype.Text
	ProfileFieldID pgtype.UUID
	Lang           string
}

func (q *Queries) UpdateProfileFieldText(ctx context.Context, arg UpdateProfileFieldTextParams) (ProfileFieldText, error) {
	row := q.db.QueryRow(ctx, updateProfileFieldText,
		arg.Content,
		arg.ModelVersion,
		arg.ProfileFieldID,
		arg.Lang,
	)
	var i ProfileFieldText
	err := row.Scan(
		&i.ProfileFieldID,
		&i.Lang,
		&i.Content,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
