// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: company_hrs.sql

package companyhrs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanyHRs = `-- name: CountCompanyHRs :one
SELECT count(*) FROM company_hrs
`

func (q *Queries) CountCompanyHRs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanyHRs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompanyHR = `-- name: CreateCompanyHR :one
INSERT INTO company_hrs (
    id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, company_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, now()
)
RETURNING id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
`

type CreateCompanyHRParams struct {
	ID         pgtype.UUID
	FirstName  string
	LastName   string
	Patronymic pgtype.Text
	Phone      pgtype.Text
	Telegram   pgtype.Text
	TelegramID pgtype.Text
	Email      pgtype.Text
	Position   pgtype.Text
	Status     string
	CompanyID  pgtype.UUID
}

func (q *Queries) CreateCompanyHR(ctx context.Context, arg CreateCompanyHRParams) (CompanyHr, error) {
	row := q.db.QueryRow(ctx, createCompanyHR,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Phone,
		arg.Telegram,
		arg.TelegramID,
		arg.Email,
		arg.Position,
		arg.Status,
		arg.CompanyID,
	)
	var i CompanyHr
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.TelegramID,
		&i.Email,
		&i.Position,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}

const deleteCompanyHR = `-- name: DeleteCompanyHR :exec
DELETE FROM company_hrs
WHERE id = $1
`

func (q *Queries) DeleteCompanyHR(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompanyHR, id)
	return err
}

const getCompanyHRByEmail = `-- name: GetCompanyHRByEmail :one
SELECT id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
FROM company_hrs
WHERE email = $1
`

func (q *Queries) GetCompanyHRByEmail(ctx context.Context, email pgtype.Text) (CompanyHr, error) {
	row := q.db.QueryRow(ctx, getCompanyHRByEmail, email)
	var i CompanyHr
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.TelegramID,
		&i.Email,
		&i.Position,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}

const getCompanyHRByID = `-- name: GetCompanyHRByID :one
SELECT id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
FROM company_hrs
WHERE id = $1
`

func (q *Queries) GetCompanyHRByID(ctx context.Context, id pgtype.UUID) (CompanyHr, error) {
	row := q.db.QueryRow(ctx, getCompanyHRByID, id)
	var i CompanyHr
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.TelegramID,
		&i.Email,
		&i.Position,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}

const getCompanyHRByPhone = `-- name: GetCompanyHRByPhone :one
SELECT id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
FROM company_hrs
WHERE phone = $1
`

func (q *Queries) GetCompanyHRByPhone(ctx context.Context, phone pgtype.Text) (CompanyHr, error) {
	row := q.db.QueryRow(ctx, getCompanyHRByPhone, phone)
	var i CompanyHr
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.TelegramID,
		&i.Email,
		&i.Position,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}

const listCompanyHRs = `-- name: ListCompanyHRs :many
SELECT id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
FROM company_hrs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCompanyHRsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCompanyHRs(ctx context.Context, arg ListCompanyHRsParams) ([]CompanyHr, error) {
	rows, err := q.db.Query(ctx, listCompanyHRs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyHr
	for rows.Next() {
		var i CompanyHr
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Patronymic,
			&i.Phone,
			&i.Telegram,
			&i.TelegramID,
			&i.Email,
			&i.Position,
			&i.Status,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompanyHRPassword = `-- name: SetCompanyHRPassword :exec
UPDATE company_hrs SET password_hash = $2 WHERE id = $1
`

type SetCompanyHRPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) SetCompanyHRPassword(ctx context.Context, arg SetCompanyHRPasswordParams) error {
	_, err := q.db.Exec(ctx, setCompanyHRPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateCompanyHR = `-- name: UpdateCompanyHR :one
UPDATE company_hrs
SET first_name = COALESCE(NULLIF($1, ''), first_name),
    last_name = COALESCE(NULLIF($2, ''), last_name),
    patronymic = COALESCE(NULLIF($3, ''), patronymic),
    phone = COALESCE(NULLIF($4, ''), phone),
    telegram = COALESCE(NULLIF($5, ''), telegram),
    telegram_id = COALESCE(NULLIF($6, ''), telegram_id),
    email = COALESCE(NULLIF($7, ''), email),
    position = COALESCE(NULLIF($8, ''), position),
    status = COALESCE(NULLIF($9, ''), status),
    company_id = CASE WHEN $10::UUID IS NOT NULL THEN $10 ELSE company_id END
WHERE id = $11
RETURNING id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    position, status, password_hash, created_at, company_id
`

type UpdateCompanyHRParams struct {
	FirstName  interface{}
	LastName   interface{}
	Patronymic interface{}
	Phone      interface{}
	Telegram   interface{}
	TelegramID interface{}
	Email      interface{}
	Position   interface{}
	Status     interface{}
	CompanyID  pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateCompanyHR(ctx context.Context, arg UpdateCompanyHRParams) (CompanyHr, error) {
	row := q.db.QueryRow(ctx, updateCompanyHR,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Phone,
		arg.Telegram,
		arg.TelegramID,
		arg.Email,
		arg.Position,
		arg.Status,
		arg.CompanyID,
		arg.ID,
	)
	var i CompanyHr
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.TelegramID,
		&i.Email,
		&i.Position,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.CompanyID,
	)
	return i, err
}
