// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, first_name, last_name, patronymic, phone, telegram, telegram_id, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, language, profile_score, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, now()
)
RETURNING id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
`

type CreateUserParams struct {
	ID              pgtype.UUID
	FirstName       string
	LastName        string
	Patronymic      pgtype.Text
	Phone           pgtype.Text
	Telegram        pgtype.Text
	TelegramID      pgtype.Text
	Email           pgtype.Text
	Gender          pgtype.Text
	Country         pgtype.Text
	Region          pgtype.Text
	Nationality     pgtype.Text
	ProfilePicUrl   pgtype.Text
	Status          string
	TariffType      string
	JobStatus       pgtype.Text
	ActivityType    pgtype.Text
	Specializations []string
	Language        string
	ProfileScore    int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Phone,
		arg.Telegram,
		arg.TelegramID,
		arg.Email,
		arg.Gender,
		arg.Country,
		arg.Region,
		arg.Nationality,
		arg.ProfilePicUrl,
		arg.Status,
		arg.TariffType,
		arg.JobStatus,
		arg.ActivityType,
		arg.Specializations,
		arg.Language,
		arg.ProfileScore,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Patronymic,
			&i.Phone,
			&i.Telegram,
			&i.Email,
			&i.Gender,
			&i.Country,
			&i.Region,
			&i.Nationality,
			&i.ProfilePicUrl,
			&i.Status,
			&i.TariffType,
			&i.JobStatus,
			&i.ActivityType,
			&i.Specializations,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.TelegramID,
			&i.Language,
			&i.ProfileScore,
			&i.EstimatedSalaryMin,
			&i.EstimatedSalaryMax,
			&i.EstimatedSalaryCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEstimatedSalary = `-- name: SetEstimatedSalary :exec
UPDATE users SET estimated_salary_min = $2, estimated_salary_max = $3, estimated_salary_currency = $4 WHERE id = $1
`

type SetEstimatedSalaryParams struct {
	ID                      pgtype.UUID
	EstimatedSalaryMin      int32
	EstimatedSalaryMax      int32
	EstimatedSalaryCurrency string
}

func (q *Queries) SetEstimatedSalary(ctx context.Context, arg SetEstimatedSalaryParams) error {
	_, err := q.db.Exec(ctx, setEstimatedSalary,
		arg.ID,
		arg.EstimatedSalaryMin,
		arg.EstimatedSalaryMax,
		arg.EstimatedSalaryCurrency,
	)
	return err
}

const setProfileScore = `-- name: SetProfileScore :exec
UPDATE users SET profile_score = $2 WHERE id = $1
`

type SetProfileScoreParams struct {
	ID           pgtype.UUID
	ProfileScore int32
}

func (q *Queries) SetProfileScore(ctx context.Context, arg SetProfileScoreParams) error {
	_, err := q.db.Exec(ctx, setProfileScore, arg.ID, arg.ProfileScore)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE(NULLIF($1, ''), first_name),
    last_name = COALESCE(NULLIF($2, ''), last_name),
    patronymic = COALESCE(NULLIF($3, ''), patronymic),
    phone = COALESCE(NULLIF($4, ''), phone),
    telegram = COALESCE(NULLIF($5, ''), telegram),
    telegram_id = COALESCE(NULLIF($6, ''), telegram_id),
    email = COALESCE(NULLIF($7, ''), email),
    gender = COALESCE(NULLIF($8, ''), gender),
    country = COALESCE(NULLIF($9, ''), country),
    region = COALESCE(NULLIF($10, ''), region),
    nationality = COALESCE(NULLIF($11, ''), nationality),
    profile_pic_url = COALESCE(NULLIF($12, ''), profile_pic_url),
    status = COALESCE(NULLIF($13, ''), status),
    tariff_type = COALESCE(NULLIF($14, ''), tariff_type),
    job_status = COALESCE(NULLIF($15, ''), job_status),
    activity_type = COALESCE(NULLIF($16, ''), activity_type),
    specializations = CASE WHEN $17::TEXT[] = '{}' THEN specializations ELSE $17 END,
    language = COALESCE(NULLIF($18, ''), language)
WHERE id = $19
RETURNING id, first_name, last_name, patronymic, phone, telegram, email,
    gender, country, region, nationality, profile_pic_url,
    status, tariff_type, job_status, activity_type, specializations, created_at, password_hash, telegram_id, language, profile_score, estimated_salary_min, estimated_salary_max, estimated_salary_currency
`

type UpdateUserParams struct {
	FirstName       interface{}
	LastName        interface{}
	Patronymic      interface{}
	Phone           interface{}
	Telegram        interface{}
	TelegramID      interface{}
	Email           interface{}
	Gender          interface{}
	Country         interface{}
	Region          interface{}
	Nationality     interface{}
	ProfilePicUrl   interface{}
	Status          interface{}
	TariffType      interface{}
	JobStatus       interface{}
	ActivityType    interface{}
	Specializations []string
	Language        interface{}
	ID              pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Patronymic,
		arg.Phone,
		arg.Telegram,
		arg.TelegramID,
		arg.Email,
		arg.Gender,
		arg.Country,
		arg.Region,
		arg.Nationality,
		arg.ProfilePicUrl,
		arg.Status,
		arg.TariffType,
		arg.JobStatus,
		arg.ActivityType,
		arg.Specializations,
		arg.Language,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Patronymic,
		&i.Phone,
		&i.Telegram,
		&i.Email,
		&i.Gender,
		&i.Country,
		&i.Region,
		&i.Nationality,
		&i.ProfilePicUrl,
		&i.Status,
		&i.TariffType,
		&i.JobStatus,
		&i.ActivityType,
		&i.Specializations,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.TelegramID,
		&i.Language,
		&i.ProfileScore,
		&i.EstimatedSalaryMin,
		&i.EstimatedSalaryMax,
		&i.EstimatedSalaryCurrency,
	)
	return i, err
}
