// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hr_sessions.sql

package hrsessions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHRSession = `-- name: CreateHRSession :one
INSERT INTO hr_sessions (id, hr_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted)
VALUES ($1, $2, $3, $4, $5, $6, now(), false)
RETURNING id, hr_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
`

type CreateHRSessionParams struct {
	ID               pgtype.UUID
	HrID             pgtype.UUID
	DeviceID         string
	RefreshTokenHash string
	FcmToken         pgtype.Text
	IpAddress        pgtype.Text
}

func (q *Queries) CreateHRSession(ctx context.Context, arg CreateHRSessionParams) (HrSession, error) {
	row := q.db.QueryRow(ctx, createHRSession,
		arg.ID,
		arg.HrID,
		arg.DeviceID,
		arg.RefreshTokenHash,
		arg.FcmToken,
		arg.IpAddress,
	)
	var i HrSession
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const getHRSessionByDeviceID = `-- name: GetHRSessionByDeviceID :one
SELECT id, hr_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
FROM hr_sessions
WHERE hr_id = $1 AND device_id = $2 AND deleted = false
`

type GetHRSessionByDeviceIDParams struct {
	HrID     pgtype.UUID
	DeviceID string
}

func (q *Queries) GetHRSessionByDeviceID(ctx context.Context, arg GetHRSessionByDeviceIDParams) (HrSession, error) {
	row := q.db.QueryRow(ctx, getHRSessionByDeviceID, arg.HrID, arg.DeviceID)
	var i HrSession
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const getHRSessionByID = `-- name: GetHRSessionByID :one
SELECT id, hr_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
FROM hr_sessions
WHERE id = $1 AND deleted = false
`

func (q *Queries) GetHRSessionByID(ctx context.Context, id pgtype.UUID) (HrSession, error) {
	row := q.db.QueryRow(ctx, getHRSessionByID, id)
	var i HrSession
	err := row.Scan(
		&i.ID,
		&i.HrID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteHRSession = `-- name: SoftDeleteHRSession :exec
UPDATE hr_sessions SET deleted = true WHERE id = $1
`

func (q *Queries) SoftDeleteHRSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHRSession, id)
	return err
}

const softDeleteHRSessions = `-- name: SoftDeleteHRSessions :exec
UPDATE hr_sessions SET deleted = true WHERE hr_id = $1
`

func (q *Queries) SoftDeleteHRSessions(ctx context.Context, hrID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHRSessions, hrID)
	return err
}

const updateHRSessionRefreshToken = `-- name: UpdateHRSessionRefreshToken :exec
UPDATE hr_sessions SET refresh_token_hash = $2 WHERE id = $1
`

type UpdateHRSessionRefreshTokenParams struct {
	ID               pgtype.UUID
	RefreshTokenHash string
}

func (q *Queries) UpdateHRSessionRefreshToken(ctx context.Context, arg UpdateHRSessionRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateHRSessionRefreshToken, arg.ID, arg.RefreshTokenHash)
	return err
}
