// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vacancy_texts.sql

package vacancytexts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVacancyText = `-- name: CreateVacancyText :one
INSERT INTO vacancy_texts (
    vacancy_id, lang, title, description, responsibilities,
    requirements, benefits, is_source, model_version, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now()
)
RETURNING vacancy_id, lang, title, description, responsibilities,
    requirements, benefits, is_source, model_version, updated_at
`

type CreateVacancyTextParams struct {
	VacancyID        pgtype.UUID
	Lang             string
	Title            string
	Description      string
	Responsibilities string
	Requirements     string
	Benefits         string
	IsSource         bool
	ModelVersion     pgtype.Text
}

func (q *Queries) CreateVacancyText(ctx context.Context, arg CreateVacancyTextParams) (VacancyText, error) {
	row := q.db.QueryRow(ctx, createVacancyText,
		arg.VacancyID,
		arg.Lang,
		arg.Title,
		arg.Description,
		arg.Responsibilities,
		arg.Requirements,
		arg.Benefits,
		arg.IsSource,
		arg.ModelVersion,
	)
	var i VacancyText
	err := row.Scan(
		&i.VacancyID,
		&i.Lang,
		&i.Title,
		&i.Description,
		&i.Responsibilities,
		&i.Requirements,
		&i.Benefits,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVacancyText = `-- name: DeleteVacancyText :exec
DELETE FROM vacancy_texts WHERE vacancy_id = $1 AND lang = $2
`

type DeleteVacancyTextParams struct {
	VacancyID pgtype.UUID
	Lang      string
}

func (q *Queries) DeleteVacancyText(ctx context.Context, arg DeleteVacancyTextParams) error {
	_, err := q.db.Exec(ctx, deleteVacancyText, arg.VacancyID, arg.Lang)
	return err
}

const deleteVacancyTextsByVacancy = `-- name: DeleteVacancyTextsByVacancy :exec
DELETE FROM vacancy_texts WHERE vacancy_id = $1
`

func (q *Queries) DeleteVacancyTextsByVacancy(ctx context.Context, vacancyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancyTextsByVacancy, vacancyID)
	return err
}

const getVacancyText = `-- name: GetVacancyText :one
SELECT vacancy_id, lang, title, description, responsibilities,
    requirements, benefits, is_source, model_version, updated_at
FROM vacancy_texts
WHERE vacancy_id = $1 AND lang = $2
`

type GetVacancyTextParams struct {
	VacancyID pgtype.UUID
	Lang      string
}

func (q *Queries) GetVacancyText(ctx context.Context, arg GetVacancyTextParams) (VacancyText, error) {
	row := q.db.QueryRow(ctx, getVacancyText, arg.VacancyID, arg.Lang)
	var i VacancyText
	err := row.Scan(
		&i.VacancyID,
		&i.Lang,
		&i.Title,
		&i.Description,
		&i.Responsibilities,
		&i.Requirements,
		&i.Benefits,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listVacancyTextsByVacancy = `-- name: ListVacancyTextsByVacancy :many
SELECT vacancy_id, lang, title, description, responsibilities,
    requirements, benefits, is_source, model_version, updated_at
FROM vacancy_texts
WHERE vacancy_id = $1
`

func (q *Queries) ListVacancyTextsByVacancy(ctx context.Context, vacancyID pgtype.UUID) ([]VacancyText, error) {
	rows, err := q.db.Query(ctx, listVacancyTextsByVacancy, vacancyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancyText
	for rows.Next() {
		var i VacancyText
		if err := rows.Scan(
			&i.VacancyID,
			&i.Lang,
			&i.Title,
			&i.Description,
			&i.Responsibilities,
			&i.Requirements,
			&i.Benefits,
			&i.IsSource,
			&i.ModelVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacancyText = `-- name: UpdateVacancyText :one
UPDATE vacancy_texts
SET title = COALESCE(NULLIF($1, ''), title),
    description = COALESCE(NULLIF($2, ''), description),
    responsibilities = COALESCE(NULLIF($3, ''), responsibilities),
    requirements = COALESCE(NULLIF($4, ''), requirements),
    benefits = COALESCE(NULLIF($5, ''), benefits),
    is_source = $6,
    model_version = $7,
    updated_at = now()
WHERE vacancy_id = $8 AND lang = $9
RETURNING vacancy_id, lang, title, description, responsibilities,
    requirements, benefits, is_source, model_version, updated_at
`

type UpdateVacancyTextParams struct {
	Title            interface{}
	Description      interface{}
	Responsibilities interface{}
	Requirements     interface{}
	Benefits         interface{}
	IsSource         bool
	ModelVersion     pgtype.Text
	VacancyID        pgtype.UUID
	Lang             string
}

func (q *Queries) UpdateVacancyText(ctx context.Context, arg UpdateVacancyTextParams) (VacancyText, error) {
	row := q.db.QueryRow(ctx, updateVacancyText,
		arg.Title,
		arg.Description,
		arg.Responsibilities,
		arg.Requirements,
		arg.Benefits,
		arg.IsSource,
		arg.ModelVersion,
		arg.VacancyID,
		arg.Lang,
	)
	var i VacancyText
	err := row.Scan(
		&i.VacancyID,
		&i.Lang,
		&i.Title,
		&i.Description,
		&i.Responsibilities,
		&i.Requirements,
		&i.Benefits,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
