// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: experience_items.sql

package experienceitems

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExperienceItem = `-- name: CreateExperienceItem :one
INSERT INTO experience_items (id, user_id, company, position, start_date, end_date, projects, web_site, item_order, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, user_id, company, position, start_date, end_date, projects, web_site, item_order, updated_at
`

type CreateExperienceItemParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Company   string
	Position  string
	StartDate pgtype.Text
	EndDate   pgtype.Text
	Projects  pgtype.Text
	WebSite   pgtype.Text
	ItemOrder int32
}

func (q *Queries) CreateExperienceItem(ctx context.Context, arg CreateExperienceItemParams) (ExperienceItem, error) {
	row := q.db.QueryRow(ctx, createExperienceItem,
		arg.ID,
		arg.UserID,
		arg.Company,
		arg.Position,
		arg.StartDate,
		arg.EndDate,
		arg.Projects,
		arg.WebSite,
		arg.ItemOrder,
	)
	var i ExperienceItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Projects,
		&i.WebSite,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExperienceItem = `-- name: DeleteExperienceItem :exec
DELETE FROM experience_items WHERE id = $1
`

func (q *Queries) DeleteExperienceItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperienceItem, id)
	return err
}

const deleteExperienceItemsByUser = `-- name: DeleteExperienceItemsByUser :exec
DELETE FROM experience_items WHERE user_id = $1
`

func (q *Queries) DeleteExperienceItemsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperienceItemsByUser, userID)
	return err
}

const getExperienceItemByID = `-- name: GetExperienceItemByID :one
SELECT id, user_id, company, position, start_date, end_date, projects, web_site, item_order, updated_at
FROM experience_items
WHERE id = $1
`

func (q *Queries) GetExperienceItemByID(ctx context.Context, id pgtype.UUID) (ExperienceItem, error) {
	row := q.db.QueryRow(ctx, getExperienceItemByID, id)
	var i ExperienceItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Projects,
		&i.WebSite,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listExperienceItemsByUser = `-- name: ListExperienceItemsByUser :many
SELECT id, user_id, company, position, start_date, end_date, projects, web_site, item_order, updated_at
FROM experience_items
WHERE user_id = $1
ORDER BY item_order
`

func (q *Queries) ListExperienceItemsByUser(ctx context.Context, userID pgtype.UUID) ([]ExperienceItem, error) {
	rows, err := q.db.Query(ctx, listExperienceItemsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExperienceItem
	for rows.Next() {
		var i ExperienceItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Company,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Projects,
			&i.WebSite,
			&i.ItemOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExperienceItem = `-- name: UpdateExperienceItem :one
UPDATE experience_items
SET company = COALESCE(NULLIF($1, ''), company),
    position = COALESCE(NULLIF($2, ''), position),
    start_date = COALESCE(NULLIF($3, ''), start_date),
    end_date = COALESCE(NULLIF($4, ''), end_date),
    projects = COALESCE(NULLIF($5, ''), projects),
    web_site = COALESCE(NULLIF($6, ''), web_site),
    item_order = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, user_id, company, position, start_date, end_date, projects, web_site, item_order, updated_at
`

type UpdateExperienceItemParams struct {
	Company   interface{}
	Position  interface{}
	StartDate interface{}
	EndDate   interface{}
	Projects  interface{}
	WebSite   interface{}
	ItemOrder int32
	ID        pgtype.UUID
}

func (q *Queries) UpdateExperienceItem(ctx context.Context, arg UpdateExperienceItemParams) (ExperienceItem, error) {
	row := q.db.QueryRow(ctx, updateExperienceItem,
		arg.Company,
		arg.Position,
		arg.StartDate,
		arg.EndDate,
		arg.Projects,
		arg.WebSite,
		arg.ItemOrder,
		arg.ID,
	)
	var i ExperienceItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Company,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Projects,
		&i.WebSite,
		&i.ItemOrder,
		&i.UpdatedAt,
	)
	return i, err
}
