// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package experienceitems

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EducationItem struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Institution  string
	Degree       string
	FieldOfStudy pgtype.Text
	StartDate    pgtype.Text
	EndDate      pgtype.Text
	Location     pgtype.Text
	ItemOrder    int32
	UpdatedAt    pgtype.Timestamp
}

type ExperienceItem struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Company   string
	Position  string
	StartDate pgtype.Text
	EndDate   pgtype.Text
	Projects  pgtype.Text
	WebSite   pgtype.Text
	ItemOrder int32
	UpdatedAt pgtype.Timestamp
}

type ItemText struct {
	ItemID       pgtype.UUID
	ItemType     string
	Lang         string
	Description  string
	IsSource     bool
	ModelVersion pgtype.Text
	UpdatedAt    pgtype.Timestamp
}

type ProfileField struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FieldName  string
	SourceLang string
	UpdatedAt  pgtype.Timestamp
}

type ProfileFieldText struct {
	ProfileFieldID pgtype.UUID
	Lang           string
	Content        string
	IsSource       bool
	ModelVersion   pgtype.Text
	UpdatedAt      pgtype.Timestamp
}

type Skill struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID              pgtype.UUID
	FirstName       string
	LastName        string
	Patronymic      pgtype.Text
	Phone           pgtype.Text
	Telegram        pgtype.Text
	Email           pgtype.Text
	Gender          pgtype.Text
	Country         pgtype.Text
	Region          pgtype.Text
	Nationality     pgtype.Text
	ProfilePicUrl   pgtype.Text
	Status          string
	TariffType      string
	JobStatus       pgtype.Text
	ActivityType    pgtype.Text
	Specializations []string
	CreatedAt       pgtype.Timestamp
}

type UserSkill struct {
	UserID  pgtype.UUID
	SkillID pgtype.UUID
}
