// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sessions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (id, user_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted)
VALUES ($1, $2, $3, $4, $5, $6, now(), false)
RETURNING id, user_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
`

type CreateSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	DeviceID         string
	RefreshTokenHash string
	FcmToken         pgtype.Text
	IpAddress        pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.RefreshTokenHash,
		arg.FcmToken,
		arg.IpAddress,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const getSessionByDeviceID = `-- name: GetSessionByDeviceID :one
SELECT id, user_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
FROM user_sessions
WHERE user_id = $1 AND device_id = $2 AND deleted = false
`

type GetSessionByDeviceIDParams struct {
	UserID   pgtype.UUID
	DeviceID string
}

func (q *Queries) GetSessionByDeviceID(ctx context.Context, arg GetSessionByDeviceIDParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByDeviceID, arg.UserID, arg.DeviceID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_id, refresh_token_hash, fcm_token, ip_address, created_at, deleted
FROM user_sessions
WHERE id = $1 AND deleted = false
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RefreshTokenHash,
		&i.FcmToken,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE user_sessions SET deleted = true WHERE id = $1
`

func (q *Queries) SoftDeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}

const softDeleteUserSessions = `-- name: SoftDeleteUserSessions :exec
UPDATE user_sessions SET deleted = true WHERE user_id = $1
`

func (q *Queries) SoftDeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUserSessions, userID)
	return err
}

const updateSessionRefreshToken = `-- name: UpdateSessionRefreshToken :exec
UPDATE user_sessions SET refresh_token_hash = $2 WHERE id = $1
`

type UpdateSessionRefreshTokenParams struct {
	ID               pgtype.UUID
	RefreshTokenHash string
}

func (q *Queries) UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionRefreshToken, arg.ID, arg.RefreshTokenHash)
	return err
}
