// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profile_fields.sql

package profilefields

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfileField = `-- name: CreateProfileField :one
INSERT INTO profile_fields (id, user_id, field_name, source_lang, updated_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, field_name, source_lang, updated_at
`

type CreateProfileFieldParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FieldName  string
	SourceLang string
}

func (q *Queries) CreateProfileField(ctx context.Context, arg CreateProfileFieldParams) (ProfileField, error) {
	row := q.db.QueryRow(ctx, createProfileField,
		arg.ID,
		arg.UserID,
		arg.FieldName,
		arg.SourceLang,
	)
	var i ProfileField
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldName,
		&i.SourceLang,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfileField = `-- name: DeleteProfileField :exec
DELETE FROM profile_fields
WHERE id = $1
`

func (q *Queries) DeleteProfileField(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileField, id)
	return err
}

const deleteProfileFieldsByUser = `-- name: DeleteProfileFieldsByUser :exec
DELETE FROM profile_fields
WHERE user_id = $1
`

func (q *Queries) DeleteProfileFieldsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileFieldsByUser, userID)
	return err
}

const getProfileFieldByID = `-- name: GetProfileFieldByID :one
SELECT id, user_id, field_name, source_lang, updated_at
FROM profile_fields
WHERE id = $1
`

func (q *Queries) GetProfileFieldByID(ctx context.Context, id pgtype.UUID) (ProfileField, error) {
	row := q.db.QueryRow(ctx, getProfileFieldByID, id)
	var i ProfileField
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldName,
		&i.SourceLang,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileFieldByUserAndName = `-- name: GetProfileFieldByUserAndName :one
SELECT id, user_id, field_name, source_lang, updated_at
FROM profile_fields
WHERE user_id = $1 AND field_name = $2
`

type GetProfileFieldByUserAndNameParams struct {
	UserID    pgtype.UUID
	FieldName string
}

func (q *Queries) GetProfileFieldByUserAndName(ctx context.Context, arg GetProfileFieldByUserAndNameParams) (ProfileField, error) {
	row := q.db.QueryRow(ctx, getProfileFieldByUserAndName, arg.UserID, arg.FieldName)
	var i ProfileField
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldName,
		&i.SourceLang,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfileFieldsByUser = `-- name: ListProfileFieldsByUser :many
SELECT id, user_id, field_name, source_lang, updated_at
FROM profile_fields
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListProfileFieldsByUser(ctx context.Context, userID pgtype.UUID) ([]ProfileField, error) {
	rows, err := q.db.Query(ctx, listProfileFieldsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileField
	for rows.Next() {
		var i ProfileField
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FieldName,
			&i.SourceLang,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileField = `-- name: UpdateProfileField :one
UPDATE profile_fields
SET field_name = COALESCE(NULLIF($1, ''), field_name),
    source_lang = COALESCE(NULLIF($2, ''), source_lang),
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, field_name, source_lang, updated_at
`

type UpdateProfileFieldParams struct {
	FieldName  interface{}
	SourceLang interface{}
	ID         pgtype.UUID
}

func (q *Queries) UpdateProfileField(ctx context.Context, arg UpdateProfileFieldParams) (ProfileField, error) {
	row := q.db.QueryRow(ctx, updateProfileField, arg.FieldName, arg.SourceLang, arg.ID)
	var i ProfileField
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FieldName,
		&i.SourceLang,
		&i.UpdatedAt,
	)
	return i, err
}
