// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: companies.sql

package companies

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*) FROM companies
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    id, employee_count, country, address, phone, telegram, telegram_channel,
    email, logo_url, web_site, instagram, source_lang, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, now()
)
RETURNING id, employee_count, country, address, phone, telegram, telegram_channel,
    email, logo_url, web_site, instagram, source_lang, created_at
`

type CreateCompanyParams struct {
	ID              pgtype.UUID
	EmployeeCount   pgtype.Int4
	Country         pgtype.Text
	Address         pgtype.Text
	Phone           pgtype.Text
	Telegram        pgtype.Text
	TelegramChannel pgtype.Text
	Email           pgtype.Text
	LogoUrl         pgtype.Text
	WebSite         pgtype.Text
	Instagram       pgtype.Text
	SourceLang      string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.EmployeeCount,
		arg.Country,
		arg.Address,
		arg.Phone,
		arg.Telegram,
		arg.TelegramChannel,
		arg.Email,
		arg.LogoUrl,
		arg.WebSite,
		arg.Instagram,
		arg.SourceLang,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.EmployeeCount,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Telegram,
		&i.TelegramChannel,
		&i.Email,
		&i.LogoUrl,
		&i.WebSite,
		&i.Instagram,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, employee_count, country, address, phone, telegram, telegram_channel,
    email, logo_url, web_site, instagram, source_lang, created_at
FROM companies
WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.EmployeeCount,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Telegram,
		&i.TelegramChannel,
		&i.Email,
		&i.LogoUrl,
		&i.WebSite,
		&i.Instagram,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, employee_count, country, address, phone, telegram, telegram_channel,
    email, logo_url, web_site, instagram, source_lang, created_at
FROM companies
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCount,
			&i.Country,
			&i.Address,
			&i.Phone,
			&i.Telegram,
			&i.TelegramChannel,
			&i.Email,
			&i.LogoUrl,
			&i.WebSite,
			&i.Instagram,
			&i.SourceLang,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET employee_count = CASE WHEN $1::INT = 0 THEN employee_count ELSE $1 END,
    country = COALESCE(NULLIF($2, ''), country),
    address = COALESCE(NULLIF($3, ''), address),
    phone = COALESCE(NULLIF($4, ''), phone),
    telegram = COALESCE(NULLIF($5, ''), telegram),
    telegram_channel = COALESCE(NULLIF($6, ''), telegram_channel),
    email = COALESCE(NULLIF($7, ''), email),
    logo_url = COALESCE(NULLIF($8, ''), logo_url),
    web_site = COALESCE(NULLIF($9, ''), web_site),
    instagram = COALESCE(NULLIF($10, ''), instagram)
WHERE id = $11
RETURNING id, employee_count, country, address, phone, telegram, telegram_channel,
    email, logo_url, web_site, instagram, source_lang, created_at
`

type UpdateCompanyParams struct {
	EmployeeCount   int32
	Country         interface{}
	Address         interface{}
	Phone           interface{}
	Telegram        interface{}
	TelegramChannel interface{}
	Email           interface{}
	LogoUrl         interface{}
	WebSite         interface{}
	Instagram       interface{}
	ID              pgtype.UUID
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.EmployeeCount,
		arg.Country,
		arg.Address,
		arg.Phone,
		arg.Telegram,
		arg.TelegramChannel,
		arg.Email,
		arg.LogoUrl,
		arg.WebSite,
		arg.Instagram,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.EmployeeCount,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Telegram,
		&i.TelegramChannel,
		&i.Email,
		&i.LogoUrl,
		&i.WebSite,
		&i.Instagram,
		&i.SourceLang,
		&i.CreatedAt,
	)
	return i, err
}
