// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vacancy_applications.sql

package vacancyapplications

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVacancyApplicationsByUser = `-- name: CountVacancyApplicationsByUser :one
SELECT count(*) FROM vacancy_applications WHERE user_id = $1
`

func (q *Queries) CountVacancyApplicationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVacancyApplicationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVacancyApplicationsByVacancy = `-- name: CountVacancyApplicationsByVacancy :one
SELECT count(*) FROM vacancy_applications WHERE vacancy_id = $1
`

func (q *Queries) CountVacancyApplicationsByVacancy(ctx context.Context, vacancyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVacancyApplicationsByVacancy, vacancyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVacancyApplication = `-- name: CreateVacancyApplication :one
INSERT INTO vacancy_applications (
    id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, now(), now()
)
RETURNING id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
`

type CreateVacancyApplicationParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	VacancyID   pgtype.UUID
	Status      string
	CoverLetter pgtype.Text
}

func (q *Queries) CreateVacancyApplication(ctx context.Context, arg CreateVacancyApplicationParams) (VacancyApplication, error) {
	row := q.db.QueryRow(ctx, createVacancyApplication,
		arg.ID,
		arg.UserID,
		arg.VacancyID,
		arg.Status,
		arg.CoverLetter,
	)
	var i VacancyApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VacancyID,
		&i.Status,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVacancyApplication = `-- name: DeleteVacancyApplication :exec
DELETE FROM vacancy_applications WHERE id = $1
`

func (q *Queries) DeleteVacancyApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancyApplication, id)
	return err
}

const deleteVacancyApplicationsByUser = `-- name: DeleteVacancyApplicationsByUser :exec
DELETE FROM vacancy_applications WHERE user_id = $1
`

func (q *Queries) DeleteVacancyApplicationsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancyApplicationsByUser, userID)
	return err
}

const deleteVacancyApplicationsByVacancy = `-- name: DeleteVacancyApplicationsByVacancy :exec
DELETE FROM vacancy_applications WHERE vacancy_id = $1
`

func (q *Queries) DeleteVacancyApplicationsByVacancy(ctx context.Context, vacancyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancyApplicationsByVacancy, vacancyID)
	return err
}

const getVacancyApplicationByID = `-- name: GetVacancyApplicationByID :one
SELECT id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
FROM vacancy_applications
WHERE id = $1
`

func (q *Queries) GetVacancyApplicationByID(ctx context.Context, id pgtype.UUID) (VacancyApplication, error) {
	row := q.db.QueryRow(ctx, getVacancyApplicationByID, id)
	var i VacancyApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VacancyID,
		&i.Status,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacancyApplicationByUserAndVacancy = `-- name: GetVacancyApplicationByUserAndVacancy :one
SELECT id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
FROM vacancy_applications
WHERE user_id = $1 AND vacancy_id = $2
`

type GetVacancyApplicationByUserAndVacancyParams struct {
	UserID    pgtype.UUID
	VacancyID pgtype.UUID
}

func (q *Queries) GetVacancyApplicationByUserAndVacancy(ctx context.Context, arg GetVacancyApplicationByUserAndVacancyParams) (VacancyApplication, error) {
	row := q.db.QueryRow(ctx, getVacancyApplicationByUserAndVacancy, arg.UserID, arg.VacancyID)
	var i VacancyApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VacancyID,
		&i.Status,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVacancyApplicationsByUser = `-- name: ListVacancyApplicationsByUser :many
SELECT id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
FROM vacancy_applications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVacancyApplicationsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListVacancyApplicationsByUser(ctx context.Context, arg ListVacancyApplicationsByUserParams) ([]VacancyApplication, error) {
	rows, err := q.db.Query(ctx, listVacancyApplicationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancyApplication
	for rows.Next() {
		var i VacancyApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VacancyID,
			&i.Status,
			&i.CoverLetter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacancyApplicationsByVacancy = `-- name: ListVacancyApplicationsByVacancy :many
SELECT id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
FROM vacancy_applications
WHERE vacancy_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVacancyApplicationsByVacancyParams struct {
	VacancyID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListVacancyApplicationsByVacancy(ctx context.Context, arg ListVacancyApplicationsByVacancyParams) ([]VacancyApplication, error) {
	rows, err := q.db.Query(ctx, listVacancyApplicationsByVacancy, arg.VacancyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancyApplication
	for rows.Next() {
		var i VacancyApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VacancyID,
			&i.Status,
			&i.CoverLetter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVacancyApplicationStatus = `-- name: UpdateVacancyApplicationStatus :one
UPDATE vacancy_applications
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, vacancy_id, status, cover_letter, created_at, updated_at
`

type UpdateVacancyApplicationStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateVacancyApplicationStatus(ctx context.Context, arg UpdateVacancyApplicationStatusParams) (VacancyApplication, error) {
	row := q.db.QueryRow(ctx, updateVacancyApplicationStatus, arg.ID, arg.Status)
	var i VacancyApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VacancyID,
		&i.Status,
		&i.CoverLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
