// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: item_texts.sql

package itemtexts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemText = `-- name: CreateItemText :one
INSERT INTO item_texts (item_id, item_type, lang, description, is_source, model_version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING item_id, item_type, lang, description, is_source, model_version, updated_at
`

type CreateItemTextParams struct {
	ItemID       pgtype.UUID
	ItemType     string
	Lang         string
	Description  string
	IsSource     bool
	ModelVersion pgtype.Text
}

func (q *Queries) CreateItemText(ctx context.Context, arg CreateItemTextParams) (ItemText, error) {
	row := q.db.QueryRow(ctx, createItemText,
		arg.ItemID,
		arg.ItemType,
		arg.Lang,
		arg.Description,
		arg.IsSource,
		arg.ModelVersion,
	)
	var i ItemText
	err := row.Scan(
		&i.ItemID,
		&i.ItemType,
		&i.Lang,
		&i.Description,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemText = `-- name: DeleteItemText :exec
DELETE FROM item_texts WHERE item_id = $1 AND item_type = $2 AND lang = $3
`

type DeleteItemTextParams struct {
	ItemID   pgtype.UUID
	ItemType string
	Lang     string
}

func (q *Queries) DeleteItemText(ctx context.Context, arg DeleteItemTextParams) error {
	_, err := q.db.Exec(ctx, deleteItemText, arg.ItemID, arg.ItemType, arg.Lang)
	return err
}

const deleteItemTextsByItem = `-- name: DeleteItemTextsByItem :exec
DELETE FROM item_texts WHERE item_id = $1 AND item_type = $2
`

type DeleteItemTextsByItemParams struct {
	ItemID   pgtype.UUID
	ItemType string
}

func (q *Queries) DeleteItemTextsByItem(ctx context.Context, arg DeleteItemTextsByItemParams) error {
	_, err := q.db.Exec(ctx, deleteItemTextsByItem, arg.ItemID, arg.ItemType)
	return err
}

const deleteItemTextsByItemID = `-- name: DeleteItemTextsByItemID :exec
DELETE FROM item_texts WHERE item_id = $1
`

func (q *Queries) DeleteItemTextsByItemID(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemTextsByItemID, itemID)
	return err
}

const getItemText = `-- name: GetItemText :one
SELECT item_id, item_type, lang, description, is_source, model_version, updated_at
FROM item_texts
WHERE item_id = $1 AND item_type = $2 AND lang = $3
`

type GetItemTextParams struct {
	ItemID   pgtype.UUID
	ItemType string
	Lang     string
}

func (q *Queries) GetItemText(ctx context.Context, arg GetItemTextParams) (ItemText, error) {
	row := q.db.QueryRow(ctx, getItemText, arg.ItemID, arg.ItemType, arg.Lang)
	var i ItemText
	err := row.Scan(
		&i.ItemID,
		&i.ItemType,
		&i.Lang,
		&i.Description,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemTextsByItem = `-- name: ListItemTextsByItem :many
SELECT item_id, item_type, lang, description, is_source, model_version, updated_at
FROM item_texts
WHERE item_id = $1 AND item_type = $2
ORDER BY is_source DESC, lang
`

type ListItemTextsByItemParams struct {
	ItemID   pgtype.UUID
	ItemType string
}

func (q *Queries) ListItemTextsByItem(ctx context.Context, arg ListItemTextsByItemParams) ([]ItemText, error) {
	rows, err := q.db.Query(ctx, listItemTextsByItem, arg.ItemID, arg.ItemType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemText
	for rows.Next() {
		var i ItemText
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemType,
			&i.Lang,
			&i.Description,
			&i.IsSource,
			&i.ModelVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemText = `-- name: UpdateItemText :one
UPDATE item_texts
SET description = $1,
    model_version = $2,
    updated_at = now()
WHERE item_id = $3 AND item_type = $4 AND lang = $5
RETURNING item_id, item_type, lang, description, is_source, model_version, updated_at
`

type UpdateItemTextParams struct {
	Description  string
	ModelVersion pgtype.Text
	ItemID       pgtype.UUID
	ItemType     string
	Lang         string
}

func (q *Queries) UpdateItemText(ctx context.Context, arg UpdateItemTextParams) (ItemText, error) {
	row := q.db.QueryRow(ctx, updateItemText,
		arg.Description,
		arg.ModelVersion,
		arg.ItemID,
		arg.ItemType,
		arg.Lang,
	)
	var i ItemText
	err := row.Scan(
		&i.ItemID,
		&i.ItemType,
		&i.Lang,
		&i.Description,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
