// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: company_texts.sql

package companytexts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyText = `-- name: CreateCompanyText :one
INSERT INTO company_texts (
    company_id, lang, name, activity_type, company_type, about, market,
    is_source, model_version, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, now()
)
RETURNING company_id, lang, name, activity_type, company_type, about, market,
    is_source, model_version, updated_at
`

type CreateCompanyTextParams struct {
	CompanyID    pgtype.UUID
	Lang         string
	Name         string
	ActivityType string
	CompanyType  string
	About        string
	Market       string
	IsSource     bool
	ModelVersion pgtype.Text
}

func (q *Queries) CreateCompanyText(ctx context.Context, arg CreateCompanyTextParams) (CompanyText, error) {
	row := q.db.QueryRow(ctx, createCompanyText,
		arg.CompanyID,
		arg.Lang,
		arg.Name,
		arg.ActivityType,
		arg.CompanyType,
		arg.About,
		arg.Market,
		arg.IsSource,
		arg.ModelVersion,
	)
	var i CompanyText
	err := row.Scan(
		&i.CompanyID,
		&i.Lang,
		&i.Name,
		&i.ActivityType,
		&i.CompanyType,
		&i.About,
		&i.Market,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompanyText = `-- name: DeleteCompanyText :exec
DELETE FROM company_texts
WHERE company_id = $1 AND lang = $2
`

type DeleteCompanyTextParams struct {
	CompanyID pgtype.UUID
	Lang      string
}

func (q *Queries) DeleteCompanyText(ctx context.Context, arg DeleteCompanyTextParams) error {
	_, err := q.db.Exec(ctx, deleteCompanyText, arg.CompanyID, arg.Lang)
	return err
}

const deleteCompanyTextsByCompany = `-- name: DeleteCompanyTextsByCompany :exec
DELETE FROM company_texts
WHERE company_id = $1
`

func (q *Queries) DeleteCompanyTextsByCompany(ctx context.Context, companyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompanyTextsByCompany, companyID)
	return err
}

const getCompanyText = `-- name: GetCompanyText :one
SELECT company_id, lang, name, activity_type, company_type, about, market,
    is_source, model_version, updated_at
FROM company_texts
WHERE company_id = $1 AND lang = $2
`

type GetCompanyTextParams struct {
	CompanyID pgtype.UUID
	Lang      string
}

func (q *Queries) GetCompanyText(ctx context.Context, arg GetCompanyTextParams) (CompanyText, error) {
	row := q.db.QueryRow(ctx, getCompanyText, arg.CompanyID, arg.Lang)
	var i CompanyText
	err := row.Scan(
		&i.CompanyID,
		&i.Lang,
		&i.Name,
		&i.ActivityType,
		&i.CompanyType,
		&i.About,
		&i.Market,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanyTextsByCompany = `-- name: ListCompanyTextsByCompany :many
SELECT company_id, lang, name, activity_type, company_type, about, market,
    is_source, model_version, updated_at
FROM company_texts
WHERE company_id = $1
`

func (q *Queries) ListCompanyTextsByCompany(ctx context.Context, companyID pgtype.UUID) ([]CompanyText, error) {
	rows, err := q.db.Query(ctx, listCompanyTextsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyText
	for rows.Next() {
		var i CompanyText
		if err := rows.Scan(
			&i.CompanyID,
			&i.Lang,
			&i.Name,
			&i.ActivityType,
			&i.CompanyType,
			&i.About,
			&i.Market,
			&i.IsSource,
			&i.ModelVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyText = `-- name: UpdateCompanyText :one
UPDATE company_texts
SET name = COALESCE(NULLIF($1, ''), name),
    activity_type = COALESCE(NULLIF($2, ''), activity_type),
    company_type = COALESCE(NULLIF($3, ''), company_type),
    about = COALESCE(NULLIF($4, ''), about),
    market = COALESCE(NULLIF($5, ''), market),
    is_source = $6,
    model_version = $7,
    updated_at = now()
WHERE company_id = $8 AND lang = $9
RETURNING company_id, lang, name, activity_type, company_type, about, market,
    is_source, model_version, updated_at
`

type UpdateCompanyTextParams struct {
	Name         interface{}
	ActivityType interface{}
	CompanyType  interface{}
	About        interface{}
	Market       interface{}
	IsSource     bool
	ModelVersion pgtype.Text
	CompanyID    pgtype.UUID
	Lang         string
}

func (q *Queries) UpdateCompanyText(ctx context.Context, arg UpdateCompanyTextParams) (CompanyText, error) {
	row := q.db.QueryRow(ctx, updateCompanyText,
		arg.Name,
		arg.ActivityType,
		arg.CompanyType,
		arg.About,
		arg.Market,
		arg.IsSource,
		arg.ModelVersion,
		arg.CompanyID,
		arg.Lang,
	)
	var i CompanyText
	err := row.Scan(
		&i.CompanyID,
		&i.Lang,
		&i.Name,
		&i.ActivityType,
		&i.CompanyType,
		&i.About,
		&i.Market,
		&i.IsSource,
		&i.ModelVersion,
		&i.UpdatedAt,
	)
	return i, err
}
