// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: skills.sql

package skills

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserSkill = `-- name: AddUserSkill :exec
INSERT INTO user_skills (user_id, skill_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserSkillParams struct {
	UserID  pgtype.UUID
	SkillID pgtype.UUID
}

func (q *Queries) AddUserSkill(ctx context.Context, arg AddUserSkillParams) error {
	_, err := q.db.Exec(ctx, addUserSkill, arg.UserID, arg.SkillID)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, name, created_at FROM skills WHERE id = $1
`

func (q *Queries) GetSkillByID(ctx context.Context, id pgtype.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, name, created_at FROM skills WHERE name = $1
`

func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, created_at FROM skills ORDER BY name
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSkills = `-- name: ListUserSkills :many
SELECT s.id, s.name, s.created_at
FROM skills s
JOIN user_skills us ON us.skill_id = s.id
WHERE us.user_id = $1
ORDER BY s.name
`

func (q *Queries) ListUserSkills(ctx context.Context, userID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listUserSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserSkills = `-- name: RemoveUserSkills :exec
DELETE FROM user_skills WHERE user_id = $1
`

func (q *Queries) RemoveUserSkills(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeUserSkills, userID)
	return err
}

const searchSkills = `-- name: SearchSkills :many
SELECT id, name, created_at FROM skills WHERE name LIKE $1 ORDER BY name LIMIT 20
`

func (q *Queries) SearchSkills(ctx context.Context, name string) ([]Skill, error) {
	rows, err := q.db.Query(ctx, searchSkills, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

type UpsertSkillParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill, arg.ID, arg.Name)
	var i Skill
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
