// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: countries.sql

package countries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCountries = `-- name: CountCountries :one
SELECT count(*) FROM countries
`

func (q *Queries) CountCountries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCountries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (id, name, short_code, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, name, short_code, created_at
`

type CreateCountryParams struct {
	ID        pgtype.UUID
	Name      string
	ShortCode string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry, arg.ID, arg.Name, arg.ShortCode)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCountry, id)
	return err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, short_code, created_at
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, id pgtype.UUID) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryByShortCode = `-- name: GetCountryByShortCode :one
SELECT id, name, short_code, created_at
FROM countries
WHERE short_code = $1
`

func (q *Queries) GetCountryByShortCode(ctx context.Context, shortCode string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByShortCode, shortCode)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, short_code, created_at
FROM countries
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET name = COALESCE(NULLIF($1, ''), name),
    short_code = COALESCE(NULLIF($2, ''), short_code)
WHERE id = $3
RETURNING id, name, short_code, created_at
`

type UpdateCountryParams struct {
	Name      interface{}
	ShortCode interface{}
	ID        pgtype.UUID
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry, arg.Name, arg.ShortCode, arg.ID)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}
