// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hr_saved_users.sql

package hrsavedusers

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSavedByHR = `-- name: CountSavedByHR :one
SELECT count(*) FROM hr_saved_users WHERE hr_id = $1
`

func (q *Queries) CountSavedByHR(ctx context.Context, hrID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedByHR, hrID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isSaved = `-- name: IsSaved :one
SELECT count(*) FROM hr_saved_users WHERE hr_id = $1 AND user_id = $2
`

type IsSavedParams struct {
	HrID   pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) IsSaved(ctx context.Context, arg IsSavedParams) (int64, error) {
	row := q.db.QueryRow(ctx, isSaved, arg.HrID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSavedByHR = `-- name: ListSavedByHR :many
SELECT hr_id, user_id, note, created_at
FROM hr_saved_users
WHERE hr_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSavedByHRParams struct {
	HrID   pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListSavedByHR(ctx context.Context, arg ListSavedByHRParams) ([]HrSavedUser, error) {
	rows, err := q.db.Query(ctx, listSavedByHR, arg.HrID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HrSavedUser
	for rows.Next() {
		var i HrSavedUser
		if err := rows.Scan(
			&i.HrID,
			&i.UserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUser = `-- name: SaveUser :one
INSERT INTO hr_saved_users (hr_id, user_id, note, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (hr_id, user_id) DO UPDATE SET note = EXCLUDED.note
RETURNING hr_id, user_id, note, created_at
`

type SaveUserParams struct {
	HrID   pgtype.UUID
	UserID pgtype.UUID
	Note   pgtype.Text
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (HrSavedUser, error) {
	row := q.db.QueryRow(ctx, saveUser, arg.HrID, arg.UserID, arg.Note)
	var i HrSavedUser
	err := row.Scan(
		&i.HrID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const unsaveUser = `-- name: UnsaveUser :exec
DELETE FROM hr_saved_users WHERE hr_id = $1 AND user_id = $2
`

type UnsaveUserParams struct {
	HrID   pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UnsaveUser(ctx context.Context, arg UnsaveUserParams) error {
	_, err := q.db.Exec(ctx, unsaveUser, arg.HrID, arg.UserID)
	return err
}
